  db:
    image: grafana/tns-db:9c1ab38
    command:
      - '-log.level=debug'
    ports:
      - 0.0.0.0:8000:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: job=tns/db
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    labels:
      namespace: tns
    # logging: 
    #   driver: loki
    #   options:
    #     loki-url: 'http://localhost:3100/api/prom/push'
    #     labels: namespace
    #     loki-relabel-config: |
    #       - action: replace
    #         source_labels: ["namespace","compose_service"]
    #         separator: "/"
    #         target_label: job

  app:
    image: grafana/tns-app:9c1ab38
    command:
      - '-log.level=debug'
      - 'http://db'
    links:
      - db
    ports:
      - 0.0.0.0:8001:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: job=tns/app
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    labels:
      namespace: tns
    # logging: 
    #   driver: loki
    #   options:
    #     loki-url: 'http://localhost:3100/api/prom/push'
    #     labels: namespace
    #     loki-relabel-config: |
    #       - action: replace
    #         source_labels: ["namespace","compose_service"]
    #         separator: "/"
    #         target_label: job

  loadgen:
    image: grafana/tns-loadgen:9c1ab38
    command:
      - '-log.level=debug'
      - 'http://app'
    links:
      - app
    ports:
      - 0.0.0.0:8002:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: job=tns/loadgen
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    labels:
      namespace: tns
    # logging: 
    #   driver: loki
    #   options:
    #     loki-url: 'http://localhost:3100/api/prom/push'
    #     labels: namespace

  tempo:
    image: grafana/tempo:latest
    command:
      - --config.file=/etc/tempo.yaml
    volumes:
      - ./docker/blocks/tempo/tempo.yaml:/etc/tempo.yaml
      - ./docker/blocks/tempo/tempo-data:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./docker/blocks/tempo/prometheus.yaml:/etc/prometheus.yaml
    links:
      - app
      - db
      - loadgen
    ports:
      - "9090:9090"
    labels:
      namespace: monitoring
    # logging: 
    #   driver: loki
    #   options:
    #     loki-url: 'http://localhost:3100/api/prom/push'
    #     labels: namespace

  loki:
    image: grafana/loki:main
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -table-manager.retention-period=1d
      - -table-manager.retention-deletes-enabled=true
    ports:
      - "3100:3100"
    labels:
      namespace: monitoring
    # logging: 
    #   driver: loki
    #   options:
    #     loki-url: 'http://localhost:3100/api/prom/push'
    #     labels: namespace

  pyroscope:
    image: 'grafana/pyroscope:latest'
    # environment:
    #   - PYROSCOPE_CONFIG=pyroscope.yaml
    #   - PYROSCOPE_LOG_LEVEL=debug
    ports:
      - '4040:4040'
    volumes:
      -  './docker/blocks/tempo/pyroscope.yaml:/etc/pyroscope.yaml'
    command:
      - 'server'
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: 'http://localhost:3100/loki/api/v1/push'

  agent:
    image: grafana/agent:v0.34.3
    volumes:
      - ./docker/blocks/tempo/agent.river:/etc/agent/agent.river:ro
    command: [ "run", "/etc/agent/agent.river", "--disable-reporting", "--server.http.listen-addr=0.0.0.0:12345" ]
    environment:
      - AGENT_MODE=flow
